import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";
import Script from "next/script";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <Script
          crossOrigin="anonymous"
          src="//unpkg.com/same-runtime/dist/index.global.js"
        />
      </head>
      <body suppressHydrationWarning className="antialiased">
        <header className="sticky top-0 z-50 border-b border-neutral-900 bg-[#0b0b0e]/80 backdrop-blur">
          <div className="mx-auto max-w-7xl px-6 py-4 flex items-center justify-between">
            <Link href="/" className="text-white font-semibold tracking-tight">ExoClone</Link>
            <nav className="flex items-center gap-2">
              <Link href="/" className="rounded-md px-4 py-2 text-sm text-white hover:bg-white/10">Home</Link>
              <Link href="/pricing" className="rounded-md px-4 py-2 text-sm text-white hover:bg-white/10">Pricing</Link>
              <Link href="/faq" className="rounded-md px-4 py-2 text-sm text-white hover:bg-white/10">FAQ</Link>
            </nav>
          </div>
        </header>
        <ClientBody>{children}</ClientBody>
      </body>
    </html>
  );
}
